# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise64.box"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :hostonly, "192.168.33.10"
  config.vm.forward_port 80,8080


  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
    chef.add_recipe "java"
    chef.add_recipe "jenkins"
  #   chef.json = { :mysql_password => "foo" }
  end
end
