# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.define :default do |node|
  	node.vm.box = "precise64.box"
  	node.vm.box_url = "http://files.vagrantup.com/precise64.box"
  	node.vm.network :hostonly, "192.168.33.10"
  	node.vm.forward_port 8080,8888
		node.vm.provision :shell, :inline => "gem install chef --version 11.4.4 --no-rdoc --no-ri --conservative"
	
		node.vm.provision :chef_solo do |chef|
    	chef.cookbooks_path = "cookbooks"
    	chef.add_recipe "apt"
			#chef.add_recipe "java"
    	#chef.add_recipe "jenkins::default"
 			chef.json = {
				  :java => {
    	    	:install_flavor => "oracle",
						:oracle => {
    	      	:accept_oracle_download_terms => true
    	    }
    	  },
			}
  	end
	end
end
