# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 	config.vm.box = "precise64.box"
	config.vm.guest = :linux
 	config.vm.box_url = "http://files.vagrantup.com/precise64.box"
	config.vm.network :forwarded_port, guest: 80, host: 8080
	
	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "manifests"
		puppet.manifest_file = "manifest.pp"
		puppet.module_path = "modules"
	end

end
